//  <!-- Alpine Script -->
function pricingSwitcher() {
  return {
    selected: 0,
    durations: ["Year", "6 Months", "3 Months"],
    plans: [
      {
        name: "FREE 14 DAYS TRIAL",
        headerClass: "bg-green-500",
        badge: "",
        prices: ["$0", "$0", "$0"],
        oldPrices: ["", "", ""],
        features: [
          { name: "Sale, Purchase Management", included: true },
          { name: "Accounts Management", included: true },
          { name: "Inventory Management", included: true },
          { name: "Warehouse Management", included: true },
          { name: "Courier Integration", included: false },
          { name: "Order Management", included: true },
          { name: "E-commerce Website Integration", included: false },
          { name: "Installment Management", included: true },
          { name: "Serial Product Management", included: true },
          { name: "Servicing Management", included: true },
          { name: "Production Management", included: true },
          { name: "30 Invoices (1 Month)", included: true },
          { name: "No. of User – 1", included: true },
          { name: "No. of Branch - 1", included: true },
          { name: "Online Training & Support", included: true },
        ],
        button: ["Take Free Trial"],
      },
      {
        name: "BASIC",
        headerClass: "bg-blue-500",
        badge: "",
        prices: ["$61.10", "$32.35", "$17.97"],
        oldPrices: ["$ 72", "$ 36"],
        features: [
          { name: "Sale, Purchase Management", included: true },
          { name: "Accounts Management", included: true },
          { name: "Inventory Management", included: true },
          { name: "Warehouse Management", included: false },
          { name: "Courier Integration", included: true },
          { name: "Order Management", included: true },
          { name: "E-commerce Website Integration", included: false },
          { name: "Installment Management", included: false },
          { name: "Serial Product Management", included: false },
          { name: "Servicing Management", included: false },
          { name: "Production Management", included: false },
          { name: "200 Invoices (1 Month)", included: true },
          { name: "No. of User – 1", included: true },
          { name: "No. of Branch - 0", included: false },
          { name: "Online Training & Support", included: true },
        ],
        button: ["Subscribe Now"],
      },
      {
        name: "STANDARD",
        headerClass: "bg-blue-700",
        badge: "POPULAR",
        prices: ["$101.90", "$53.95", "$29.97"],
        oldPrices: ["$120", "$60"],
        features: [
          { name: "Sale, Purchase Management", included: true },
          { name: "Accounts Management", included: true },
          { name: "Inventory Management", included: true },
          { name: "Warehouse Management", included: true },
          { name: "Courier Integration", included: true },
          { name: "Order Management", included: true },
          { name: "E-commerce Website Integration", included: true },
          { name: "Installment Management", included: true },
          { name: "Serial Product Management", included: true },
          { name: "Servicing Management", included: true },
          { name: "Production Management", included: false },
          { name: "1000 Invoices (1 Month)", included: true },
          { name: "No. of User – 5", included: true },
          { name: "No. of Branch - 1", included: true },
          { name: "Online Training & Support", included: true },
        ],
        button: ["Subscribe Now"],
      },
      {
        name: "ENTERPRISE",
        headerClass: "bg-teal-700",
        badge: "",
        prices: ["$224.30", "$118.97", "$65.97"],
        oldPrices: ["$264", "$132"],
        features: [
          { name: "Sale, Purchase Management", included: true },
          { name: "Accounts Management", included: true },
          { name: "Inventory Management", included: true },
          { name: "Warehouse Management", included: true },
          { name: "Courier Integration", included: true },
          { name: "Order Management", included: true },
          { name: "E-commerce Website Integration", included: true },
          { name: "Installment Management", included: true },
          { name: "Serial Product Management", included: true },
          { name: "Servicing Management", included: true },
          { name: "Production Management", included: true },
          { name: "5000 Invoices (1 Month)", included: true },
          { name: "No. of User – 15", included: true },
          { name: "No. of Branch - 2", included: true },
          { name: "Online Training & Support", included: true },
        ],
        button: ["Subscribe Now"],
      },
    ],
  };
}
//  swiper js
const swiper = new Swiper(".mySwiper", {
  loop: true,
  centeredSlides: true,
  slidesPerView: 3,
  spaceBetween: 30,
  autoplay: {
    delay: 3000, // 3 seconds
    disableOnInteraction: false,
  },
  pagination: {
    el: ".swiper-pagination",
    clickable: true,
  },
  breakpoints: {
    0: {
      slidesPerView: 1,
    },
    768: {
      slidesPerView: 2,
    },
    1024: {
      slidesPerView: 3,
    },
  },
});
